### ISSUE TITLE
WirePod crashes after a certain amount of time

### ISSUE THREAD

**Issue by ABUCKY0** [kercre123/wire-pod#166]
An Index out of Range error will occur semi randomly, I'm not sure what the cause is though. Logs are below
```
pi@escapepod:~/wire-pod $ sudo ./chipper/start.sh
Initializing variables
SDK info path: /home/pi/.anki_vector/
API config successfully read
Loaded jdocs file
Loaded bot info file, known bots: [00608842]
Loaded 54 intents and 54 matches (language: en-US)
Initiating vosk voice processor with language en-US
Opening VOSK model (../vosk/models/en-US/model)
VOSK initiated successfully
Loading plugins
Starting webserver at port 8080 (http://localhost:8080)
Starting SDK app
Starting server at port 80 for connCheck
Initiating TLS listener, cmux, gRPC handler, and REST handler
Configuration page: http://10.0.0.46:8080
Starting chipper server at port 443
Starting chipper server at port 8084 for 2.0.1 compatibility
wire-pod started successfully!
Starting jdocs pinger timer for 10.0.0.232:443
Successfully got jdocs from 00608842
Connecting to 00608842 with GUID YJyVCIoh/EDJHef49mxr+A==
Bot 1 Stream type: OPUS
(Bot 1, Vosk) Processing...
EOF
Bot 1 Intent Sent: intent_system_noaudio
Bot 1 Parameters Sent: map[error:EOF]
Bot 1 Stream type: OPUS
(Bot 1, Vosk) Processing...
(Bot 1) End of speech detected.
Bot 1 Transcribed text: personally
Not a custom intent
No intent was matched.
Bot 1 Intent Sent: intent_system_noaudio
No Parameters Sent
Closing SDK connection for 00608842, source: connTimer
panic: runtime error: index out of range [0] with length 0

goroutine 73 [running]:
github.com/kercre123/chipper/pkg/wirepod/sdkapp.assumeBehaviorControl.func1()
        /home/pi/wire-pod/chipper/pkg/wirepod/sdkapp/bcassume.go:82 +0x1c8
created by github.com/kercre123/chipper/pkg/wirepod/sdkapp.assumeBehaviorControl
        /home/pi/wire-pod/chipper/pkg/wirepod/sdkapp/bcassume.go:29 +0x224
```

It doesn't happen immediately, and will take a few minutes before erroring.

Edit: It occurs after idiling on the robot control screen.

**Comment by kercre123** [comment]
This has been fixed in the latest commit
