### ISSUE TITLE
Wire-pod segmentation violation if you leave web interface open overnight and then use it without refreshing

### ISSUE THREAD

**Issue by Sovenger** [kercre123/wire-pod#81]
I have the SDK enabled, daemon enabled, using VOSK, OpenAI, and Weather. HEAD is at 8c3550b5af1d672f06d57ed3685ac7e9cd97f158.

I left the web interface open overnight on a laptop that went to sleep. In the morning, I logged into the laptop, web interface was still up so I clicked Configure Bots, selected bot and connected. I believe that is when the follow errors appeared.

```
Feb 07 17:15:15 escapepod start.sh[4934]: Bot 1 Stream type: OPUS
Feb 07 17:15:15 escapepod start.sh[4934]: (Bot 1, Vosk) Processing...
Feb 07 17:15:18 escapepod start.sh[4934]: (Bot 1) End of speech detected.
Feb 07 17:15:18 escapepod start.sh[4934]: Bot 1 Transcribed text: good morning
Feb 07 17:15:18 escapepod start.sh[4934]: Not a custom intent
Feb 07 17:15:18 escapepod start.sh[4934]: Partial match for intent intent_greeting_goodmorning (morning)
Feb 07 17:15:18 escapepod start.sh[4934]: Checking params for candidate intent intent_greeting_goodmorning
Feb 07 17:15:18 escapepod start.sh[4934]: Bot 1 Intent Sent: intent_greeting_goodmorning
Feb 07 17:15:18 escapepod start.sh[4934]: No Parameters Sent
Feb 07 17:15:18 escapepod start.sh[4934]: Bot 1 request served.
Feb 07 17:47:23 escapepod start.sh[4934]: Jdocs: Incoming ReadDocs request, Robot ID: vic:<redacted>, Item(s) to return:
Feb 07 17:47:23 escapepod start.sh[4934]: [doc_name:"vic.AppTokens"]
Feb 07 17:47:24 escapepod start.sh[4934]: 2023/02/07 17:47:24 http: panic serving 192.168.1.210:58926: runtime error: invalid memory address or nil pointer dereference
Feb 07 17:47:24 escapepod start.sh[4934]: goroutine 21439 [running]:
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.(*conn).serve.func1()
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:1850 +0xbf
Feb 07 17:47:24 escapepod start.sh[4934]: panic({0x104f340, 0x17ed100})
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/runtime/panic.go:890 +0x262
Feb 07 17:47:24 escapepod start.sh[4934]: github.com/kercre123/chipper/pkg/wirepod/sdkapp.SdkapiHandler({0x129ec98?, 0xc0003fa2a0}, 0xc00043c500)
Feb 07 17:47:24 escapepod start.sh[4934]:         /home/pi/wire-pod/chipper/pkg/wirepod/sdkapp/server.go:106 +0x2a4e
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.HandlerFunc.ServeHTTP(0xc000509af0?, {0x129ec98?, 0xc0003fa2a0?}, 0x0?)
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:2109 +0x2f
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.(*ServeMux).ServeHTTP(0xc0011ba01f?, {0x129ec98, 0xc0003fa2a0}, 0xc00043c500)
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:2487 +0x149
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.serverHandler.ServeHTTP({0xc000fd2570?}, {0x129ec98, 0xc0003fa2a0}, 0xc00043c500)
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:2947 +0x30c
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.(*conn).serve(0xc000000fa0, {0x129f760, 0xc00022d8c0})
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:1991 +0x607
Feb 07 17:47:24 escapepod start.sh[4934]: created by net/http.(*Server).Serve
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:3102 +0x4db
Feb 07 17:47:24 escapepod start.sh[4934]: 2023/02/07 17:47:24 http: panic serving 192.168.1.210:58932: runtime error: invalid memory address or nil pointer dereference
Feb 07 17:47:24 escapepod start.sh[4934]: goroutine 21462 [running]:
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.(*conn).serve.func1()
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:1850 +0xbf
Feb 07 17:47:24 escapepod start.sh[4934]: panic({0x104f340, 0x17ed100})
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/runtime/panic.go:890 +0x262
Feb 07 17:47:24 escapepod start.sh[4934]: github.com/kercre123/chipper/pkg/wirepod/sdkapp.SdkapiHandler({0x129ec98?, 0xc0000d0e00}, 0xc000221e00)
Feb 07 17:47:24 escapepod start.sh[4934]:         /home/pi/wire-pod/chipper/pkg/wirepod/sdkapp/server.go:106 +0x2a4e
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.HandlerFunc.ServeHTTP(0xc000507af0?, {0x129ec98?, 0xc0000d0e00?}, 0x0?)
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:2109 +0x2f
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.(*ServeMux).ServeHTTP(0xc000a1a9df?, {0x129ec98, 0xc0000d0e00}, 0xc000221e00)
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:2487 +0x149
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.serverHandler.ServeHTTP({0xc001164d20?}, {0x129ec98, 0xc0000d0e00}, 0xc000221e00)
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:2947 +0x30c
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.(*conn).serve(0xc00021cc80, {0x129f760, 0xc00022d8c0})
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:1991 +0x607
Feb 07 17:47:24 escapepod start.sh[4934]: created by net/http.(*Server).Serve
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:3102 +0x4db
Feb 07 17:47:24 escapepod start.sh[4934]: 2023/02/07 17:47:24 http: panic serving 192.168.1.210:58924: runtime error: invalid memory address or nil pointer dereference
Feb 07 17:47:24 escapepod start.sh[4934]: goroutine 21438 [running]:
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.(*conn).serve.func1()
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:1850 +0xbf
Feb 07 17:47:24 escapepod start.sh[4934]: panic({0x104f340, 0x17ed100})
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/runtime/panic.go:890 +0x262
Feb 07 17:47:24 escapepod start.sh[4934]: github.com/kercre123/chipper/pkg/wirepod/sdkapp.SdkapiHandler({0x129ec98?, 0xc0003fa380}, 0xc000221a00)
Feb 07 17:47:24 escapepod start.sh[4934]:         /home/pi/wire-pod/chipper/pkg/wirepod/sdkapp/server.go:106 +0x2a4e
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.HandlerFunc.ServeHTTP(0xc00012daf0?, {0x129ec98?, 0xc0003fa380?}, 0x0?)
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:2109 +0x2f
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.(*ServeMux).ServeHTTP(0xc0011ba11f?, {0x129ec98, 0xc0003fa380}, 0xc000221a00)
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:2487 +0x149
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.serverHandler.ServeHTTP({0xc0011646c0?}, {0x129ec98, 0xc0003fa380}, 0xc000221a00)
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:2947 +0x30c
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.(*conn).serve(0xc000000280, {0x129f760, 0xc00022d8c0})
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:1991 +0x607
Feb 07 17:47:24 escapepod start.sh[4934]: created by net/http.(*Server).Serve
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:3102 +0x4db
Feb 07 17:47:24 escapepod start.sh[4934]: 2023/02/07 17:47:24 http: panic serving 192.168.1.210:58954: runtime error: invalid memory address or nil pointer dereference
Feb 07 17:47:24 escapepod start.sh[4934]: goroutine 21508 [running]:
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.(*conn).serve.func1()
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:1850 +0xbf
Feb 07 17:47:24 escapepod start.sh[4934]: panic({0x104f340, 0x17ed100})
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/runtime/panic.go:890 +0x262
Feb 07 17:47:24 escapepod start.sh[4934]: github.com/kercre123/chipper/pkg/wirepod/sdkapp.SdkapiHandler({0x129ec98?, 0xc0000d0ee0}, 0xc000221f00)
Feb 07 17:47:24 escapepod start.sh[4934]:         /home/pi/wire-pod/chipper/pkg/wirepod/sdkapp/server.go:106 +0x2a4e
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.HandlerFunc.ServeHTTP(0xc000a59af0?, {0x129ec98?, 0xc0000d0ee0?}, 0x0?)
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:2109 +0x2f
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.(*ServeMux).ServeHTTP(0xc000a1ab1f?, {0x129ec98, 0xc0000d0ee0}, 0xc000221f00)
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:2487 +0x149
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.serverHandler.ServeHTTP({0xc00115ffb0?}, {0x129ec98, 0xc0000d0ee0}, 0xc000221f00)
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:2947 +0x30c
Feb 07 17:47:24 escapepod start.sh[4934]: net/http.(*conn).serve(0xc00021d5e0, {0x129f760, 0xc00022d8c0})
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:1991 +0x607
Feb 07 17:47:24 escapepod start.sh[4934]: created by net/http.(*Server).Serve
Feb 07 17:47:24 escapepod start.sh[4934]:         /usr/local/go/src/net/http/server.go:3102 +0x4db
Feb 07 17:47:41 escapepod start.sh[4934]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 07 17:47:41 escapepod start.sh[4934]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xf4efb6]
Feb 07 17:47:41 escapepod start.sh[4934]: goroutine 21497 [running]:
Feb 07 17:47:41 escapepod start.sh[4934]: github.com/kercre123/chipper/pkg/wirepod/sdkapp.SdkapiHandler.func1()
Feb 07 17:47:41 escapepod start.sh[4934]:         /home/pi/wire-pod/chipper/pkg/wirepod/sdkapp/server.go:282 +0x236
Feb 07 17:47:41 escapepod start.sh[4934]: created by github.com/kercre123/chipper/pkg/wirepod/sdkapp.SdkapiHandler
Feb 07 17:47:41 escapepod start.sh[4934]:         /home/pi/wire-pod/chipper/pkg/wirepod/sdkapp/server.go:265 +0x1af6
```

**Comment by kercre123** [comment]
Just pushed some code which closes the connection after 5 minutes of inacitivty, this shouldn't be an issue anymore.
