### ISSUE TITLE
Wire-pod.service crash due to index out of range for connTimer

### ISSUE THREAD

**Issue by Sovenger** [kercre123/wire-pod#96]
My wire-pod install generated this failure last night:

```
Feb 21 19:40:11 escapepod start.sh[460]: Closing SDK connection for 00403249, source: connTimer
Feb 21 19:40:12 escapepod start.sh[460]: panic: runtime error: index out of range [0] with length 0
Feb 21 19:40:12 escapepod start.sh[460]: goroutine 208 [running]:
Feb 21 19:40:12 escapepod start.sh[460]: github.com/kercre123/chipper/pkg/wirepod/sdkapp.SdkapiHandler.func1()
Feb 21 19:40:12 escapepod start.sh[460]:         /home/pi/wire-pod/chipper/pkg/wirepod/sdkapp/server.go:285 +0x378
Feb 21 19:40:12 escapepod start.sh[460]: created by github.com/kercre123/chipper/pkg/wirepod/sdkapp.SdkapiHandler
Feb 21 19:40:12 escapepod start.sh[460]:         /home/pi/wire-pod/chipper/pkg/wirepod/sdkapp/server.go:269 +0x1a44
Feb 21 19:40:12 escapepod systemd[1]: wire-pod.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 21 19:40:12 escapepod systemd[1]: wire-pod.service: Failed with result 'exit-code'.
Feb 21 19:40:12 escapepod systemd[1]: wire-pod.service: Consumed 1min 1.706s CPU time.
```

In addition to that, what do you think about adding some restart conditions to the service so it doesn't just tank on a failure like this? Maybe we give it a chance to restart the service up to 5 times before it stops? I can make a PR for this part if you want.

```
[Unit]
Description=Wire Escape Pod (coqui)
StartLimitIntervalSec=500
StartLimitBurst=5

[Service]
Type=simple
Restart=on-failure
RestartSec=5s
WorkingDirectory=/home/pi/wire-pod/chipper
ExecStart=/home/pi/wire-pod/chipper/start.sh

[Install]
WantedBy=multi-user.target
```

**Comment by kercre123** [comment]
A fix will come in the next few commits. A PR would be appreciated for the service file

**Comment by kercre123** [comment]
The issue should be solved now. The bug was due to the event stream code trying to read a bool which was removed by the connection timeout timer.
